### ISSUE TITLE
502 Bad Gateway in https://amiunique.org/

### ISSUE THREAD

**Issue by gautamkrishnar** [plaperdr/amiunique-extension-chrome#2]
Visit https://amiunique.org/

![screenshot 2018-11-25 at 3 10 04 pm](https://user-images.githubusercontent.com/8397274/48977646-4794f200-f0c4-11e8-877b-b318a44e9be9.png)

**Comment by plaperdr** [comment]
It should be fixed now. Thanks for bringing up this issue!
